# fly.toml app configuration file generated for dailydisc on 2024-10-29T18:34:54Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dailydisc'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [[http_service.domains]]
    name = "dailydisc.club"
    zone = "dailydisc.club"

  [[http_service.domains]]
    name = "www.dailydisc.club"
    zone = "dailydisc.club"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1