name: Update Album

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every night (UTC time)

jobs:
  update-album:
    runs-on: ubuntu-latest
    steps:
      - name: Call pick album resource route
        run: |
          curl -X GET https://dailydisc.club/api/pick-album
