name: Update Album

on:
  schedule:
    # During GMT (Oct-Mar): Run at midnight UTC
    - cron: "0 0 * 10,11,12,1,2,3 *"
    # During BST (Apr-Sep): Run at 11pm UTC
    - cron: "0 23 * 4,5,6,7,8,9 *"

jobs:
  update-album:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get install jq

      - name: Call pick album resource route and send Discord message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Call the API and store the response
          response=$(curl -sS -X GET https://dailydisc.fly.dev/api/pick-album -H "x-api-key: ${{ secrets.API_KEY }}")

          # Extract the necessary information from the JSON response
          title=$(echo "$response" | jq -r '.randomAlbum.title')
          image=$(echo "$response" | jq -r '.randomAlbum.image')
          artist=$(echo "$response" | jq -r '.randomAlbum.artist')
          year=$(echo "$response" | jq -r '.randomAlbum.year')
          genre=$(echo "$response" | jq -r '.randomAlbum.genre')

          # Log the album information
          echo "Today's Album:"
          echo "Title: $title"
          echo "Artist: $artist"
          echo "Year: $year"
          echo "Genre: $genre"
          echo "Image URL: $image"

          # Prepare the Discord message payload
          payload=$(jq -n --arg title "$title" --arg image "$image" --arg artist "$artist" --arg year "$year" --arg genre "$genre" '{
            embeds: [{
              title: "Today'"'"'s Album",
              description: $title,
              fields: [
                {name: "Artist", value: $artist, inline: true},
                {name: "Year", value: $year, inline: true},
                {name: "Genre", value: $genre, inline: true}
              ],
              color: 3447003,
              image: {
                url: $image
              }
            }]
          }')

          # Send the Discord message
          curl -H "Content-Type: application/json" -d "$payload" "$DISCORD_WEBHOOK"

          echo "Discord message sent successfully!"
