name: Update Album and Send Discord Message

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  update-album:
    runs-on: ubuntu-latest
    steps:
      - name: Determine if we should run in Summer Time
        id: determine_time
        run: |
          current_month=$(date +'%m')
          if [[ "$current_month" -ge 3 && "$current_month" -le 10 ]]; then
            echo "in_summer_time=true" >> $GITHUB_ENV
          else
            echo "in_summer_time=false" >> $GITHUB_ENV
          fi

      - name: Install jq
        run: sudo apt-get install jq

      - name: Call pick album resource route and send Discord message
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Call the API and store the response
          response=$(curl -sS -X GET https://www.dailydisc.club/api/pick-album -H "x-api-key: ${{ secrets.API_KEY }}")

          # Extract the necessary information from the JSON response
          title=$(echo "$response" | jq -r '.randomAlbum.title')
          image=$(echo "$response" | jq -r '.randomAlbum.image')

          # Prepare the Discord message payload
          payload=$(jq -n --arg title "$title" --arg image "$image" '{
            embeds: [{
              title: "Today'"'"'s Album",
              description: $title,
              color: 3447003,
              image: {
                url: $image
              }
            }]
          }')

          # Send the Discord message
          curl -H "Content-Type: application/json" -d "$payload" "$DISCORD_WEBHOOK"
