- name: Call pick album resource route and send Discord message
  env:
    DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
  run: |
    # Call the API and store the response, ensuring we only get the body
    response=$(curl -sS -X GET https://www.dailydisc.club/api/pick-album -H "x-api-key: ${{ secrets.API_KEY }}")

    # Print the response for debugging (you can remove this later)
    echo "API Response:"
    echo "$response"

    # Check if the response is valid JSON
    if ! echo "$response" | jq empty; then
      echo "Error: Invalid JSON response"
      exit 1
    fi

    # Extract the necessary information from the JSON response
    title=$(echo $response | jq -r '.randomAlbum.title')
    image=$(echo $response | jq -r '.randomAlbum.image')

    # Print extracted data for debugging (you can remove this later)
    echo "Title: $title"
    echo "Image: $image"

    # Prepare the Discord message payload
    payload=$(cat <<EOF
    {
      "embeds": [{
        "title": "Today's Album",
        "description": "$title",
        "color": 3447003,
        "image": {
          "url": "$image"
        }
      }]
    }
    EOF
    )

    # Send the Discord message
    curl -H "Content-Type: application/json" -d "$payload" $DISCORD_WEBHOOK
