name: Update Album

on:
  schedule:
    # Winter Time (UTC): 12 AM UTC
    - cron: "0 0 * 11-12,1-3 *"
    # Summer Time (BST): 11 PM UTC (12 AM BST)
    - cron: "0 23 * 3-10 *"

jobs:
  update-album:
    runs-on: ubuntu-latest
    steps:
      - name: Determine if we should run in Summer Time
        id: determine_time
        run: |
          current_month=$(date +'%m')
          if [[ "$current_month" -ge 3 && "$current_month" -le 10 ]]; then
            echo "in_summer_time=true" >> $GITHUB_ENV
          else
            echo "in_summer_time=false" >> $GITHUB_ENV
          fi

      - name: Call pick album resource route in Winter Time
        if: ${{ env.in_summer_time == 'false' }}
        run: |
          curl -X GET https://www.dailydisc.club/api/pick-album -H "x-api-key: ${{ secrets.API_KEY }}"

      - name: Call pick album resource route in Summer Time
        if: ${{ env.in_summer_time == 'true' }}
        run: |
          curl -X GET https://www.dailydisc.club/api/pick-album -H "x-api-key: ${{ secrets.API_KEY }}"
